---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: "{{ .Values.certSecret }}"
spec:
  secretName: "{{ .Values.certSecret }}"
  dnsNames:
  - "{{ .Values.domainName }}"
  acme:
    config:
    - http01:
        ingressClass: "{{ .Values.ingressClass }}"
      domains:
      - "{{ .Values.domainName }}"
  issuerRef:
    name: "{{ .Values.certIssuer }}"
    kind: ClusterIssuer
